name: restaurante_app
description: Sistema de gestión para restaurantes

# La siguiente línea evita que tu paquete sea publicado accidentalmente en pub.dev
publish_to: 'none' 

# Versión del aplicativo
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  sqflite_common_ffi: ^2.2.0  # Añade esta línea
  path: ^1.8.0
  intl: ^0.18.0
  
  # Iconos de Material Design
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lint para estilo de código
  flutter_lints: ^2.0.0

# Configuración de Flutter
flutter:
  # Asegura que material design esté activado
  uses-material-design: true

  # Para agregar assets descomenta las siguientes líneas
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para agregar fuentes personalizadas descomenta las siguientes líneas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  